### ISSUE TITLE
Wrong dispersion correction for Mg

### ISSUE THREAD

**Issue by KaiSellschopp** [dftd4/dftd4#159] opened 2022-05-12 09:28 UTC
**Describe the bug**
I believe there is an error in the calculation of the dispersion correction for Mg. When I calculate the dispersion energy for different lattice constants, the dispersion correction "jumps" to less negative values for smaller lattice constants.

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with input (include input files)
   - Take the hcp structure of Mg (e.g. from COD or from attached file)
   - Change the lattice vectors by a factor (e.g. in the range 0.95 to 1.05)
2. start `dftd4` with (all the options here) `dftd4 --func pbe POSCAR` (but same behaviour occurs for other functionals, I also tried pbesol and scan)
3. output showing the error: there is a discontinuous jump in the dispersion energy (see attached files)

I attached the Mg structure file from the COD (and converted to POSCAR format), and a small script that changes the lattice constant and starts dftd4 to illustrate the problem. You can start it like this `bash d4_lattice_constant.sh [STRUCTURE] [FUNCTIONAL]`, where [STRUCTURE] is the name of the structure file (POSCAR format) and [FUNCTIONAL] is the option passed to --func. The attached "*.summary" files are some example outputs that I get, and I also plotted them to illustrate the problem.

**Expected behaviour**
I would expect a continuous increase in the dispersion energy (i.e. to less negative values) with increasing lattice constant. This is also what I observe for other materials. I tested Al and Li, structure files for both are attached for comparison, for Li I also attached the output of my script.

**Additional context**
I use the latest release of DFT-D4 and compiled it from the source code. The compilation and tests ran without any errors. There was only a warning that the option "-fortranlibs" is not known to the compiler and ignored:

[253/290] Linking Fortran executable _deps/multicharge-build/app/multicharge
ifort: command line warning #10006: ignoring unknown option '-fortranlibs'
[278/290] Linking Fortran executable _deps/multicharge-build/test/multicharge-tester
ifort: command line warning #10006: ignoring unknown option '-fortranlibs'
[286/290] Linking Fortran executable app/dftd4
ifort: command line warning #10006: ignoring unknown option '-fortranlibs'
[290/290] Linking Fortran executable test/unit/dftd4-tester
ifort: command line warning #10006: ignoring unknown option '-fortranlibs

[dftd4_issue_Mg.zip](https://github.com/dftd4/dftd4/files/8676757/dftd4_issue_Mg.zip)
'

**Comment by marvinfriede** [comment] 2024-11-06 19:46
Although this issue is quite old, here is some explanation and a potential solution.

In D4, the PES can unfortunately exhibit bumps and artificial minima when the coordinative environment (of mainly metals) changes. This is caused by the coordination number (CN) based Gaussian weighting in the calculation of the polarizability. If the CNs of the reference systems are far apart (e.g., 1, 2 and 12), the weighting formula can give unreasonable results for small changes of intermediate CNs (e.g., around 4 or 5), which are not covered by any reference system. It also caused some technical issues (see https://github.com/dftd4/dftd4/issues/223#issuecomment-1800037261).

> I would expect a continuous increase in the dispersion energy (i.e. to less negative values) with increasing lattice constant. This is also what I observe for other materials. I tested Al and Li, structure files for both are attached for comparison, for Li I also attached the output of my script.

The more negative energies can be observed for all three systems if one extends the range of scanned lattice constants in your script. All systems exhibit a weird jump in energy. For Mg, the weird jump in the PES is observed earlier (around 1.0) compared to Li and Al as pointed out by your analysis.
These sudden jumps are fixed with a smoother interpolation between the reference systems through the D4S model.

![plot](https://github.com/user-attachments/assets/dc179531-13ff-4999-a2b0-e0a1ae584def)

Nevertheless, the Mg PES still has a weird shoulder (around 1.07) and the jumps are quite steep. I believe that this can only be fixed with additional reference system that cover a wider variety of coordination numbers of the metals.
Apparently, Mg is particularly plagued by this issue as also evident in #223: Here, MgO shows weird behavior while Al2O3 works as expected).

**Closed by marvinfriede** 2024-11-06 19:46 UTC
Labels: bug
