### ISSUE TITLE
Differences between 2.4 and 3.5

### ISSUE THREAD

**Issue by martin-schlipf** [dftd4/dftd4#197] opened 2023-04-12 07:29 UTC
## The dispersion energy is different between version 2.4 and 3.5.

This example POSCAR file
~~~
C2F2
1.0
 1.291 2.23608 0.0
-1.291 2.23608 0.0
 0.0   0.0     5.75
C F
2 2
Direct
0.0                  0.0                  0.239351886956520
0.666667109405743    0.666667109405743    0.324700286956521
0.0                  0.0                  6.864365217396085E-004
0.666667109405743    0.666667109405743    0.563365737391301
~~~
with `dftd4 -f pbe POSCAR` produces the energy -0.01561764 with 2.4.0 and -0.01557027 with 3.5.0.

For context, I want to update the VASP interface to the new API, so it would be good to make sure that I reproduce the correct value. Just to be sure, I should reproduce the energy, forces, stress in the dftd4.txt file after converting them to eV and Å, shouldn't I?

**Comment by marvinfriede** [comment] 2023-04-17 16:40
I was able to reproduce the problem for the energies. After some digging, I found that the EEQ charges are different. In fact, if I use the EEQ charges of 3.5.0, I get (nearly) the same energy as with 2.4.0. (-0.01557180).
The differences start with the A-matrix ([3.5.0](https://github.com/grimme-lab/multicharge/blob/42818911d5754604504ed553dcf0b5db33f3c867/src/multicharge/model.F90#L466) and [2.4.0](https://github.com/dftd4/dftd4/blob/0984cef46daee9a6043c2df69c67c6bc8a4f9ca3/source/eeq_model.f90#L330)).

**Comment by awvwgk** [comment] 2023-04-17 17:39
As far as I recall there was an issue in the Ewald summation in version 2.4, which was fixed in 2.5 or latest with 3.0.

**Comment by marvinfriede** [comment] 2023-04-17 21:21
2.5.0 gives the same results as 2.4.0. It seems to ne fixes in 3.0.0, which gives the same results as 3.5.0.

**Comment by e-kwsm** [comment] 2023-04-19 00:04
This bisects to ec78259c2bcccc4f94709438f8676d97b0844ac3; the followings are calculated with GCC 12:

| revision | Dispersion energy / Eh |
|---|--:|
| ae8031b04534714d5ff5bc9613cba8b25dd1dcd2 | -0.01561754 |
| ec78259c2bcccc4f94709438f8676d97b0844ac3 | -1.5570274515929E-02 |

**Comment by awvwgk** [comment] 2023-04-22 10:48
Looks right then, I strongly recommend to use version 3 and later. I don't think it makes sense to backport this fix to version 2 of dftd4 since we have a compatibility layer for interfacing with Vasp available.

**Comment by awvwgk** [comment] 2023-04-22 10:51
> For context, I want to update the VASP interface to the new API, so it would be good to make sure that I reproduce the correct value. Just to be sure, I should reproduce the energy, forces, stress in the dftd4.txt file after converting them to eV and Å, shouldn't I?

Thanks that's good to hear, the output produced by the command line as in the API is always in atomic unit.

**Closed** 2023-07-11 20:52 UTC
